#!/usr/bin/env python3
"""
bmad-dl-scaffold: Project scaffolding script.

Creates the full folder structure, writes .clinerules / CLAUDE.md,
initialises a uv project, and adds a .gitignore.

No packages are installed. Dependency selection happens in bmad-dl-ideation
(Stage 1); installations run in bmad-dl-infra (Stage 5) via `uv sync`.
"""

import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# .clinerules template (Cline / Cursor / Antigravity)
# ---------------------------------------------------------------------------
CLINERULES_TEMPLATE = """\
# BMAD DL Lifecycle — Skill Reference
# Auto-generated by bmad-dl-scaffold. Edit paths if your submodule location differs.
#
# HOW TO USE (Cline / Cursor):
#   There are no slash commands. To invoke a skill, tell the AI:
#   "Follow the workflow in: <path below>"
#   or paste the path into your system prompt / context.

## Lifecycle Skills (run in order)

- Stage 1   — Frame problem / PRD:        _bmad/bmad-dl-lifecycle/bmad-dl-ideation/SKILL.md
- Stage 2   — Exploratory data analysis:  _bmad/bmad-dl-lifecycle/bmad-dl-eda/SKILL.md
- Stage 3   — Architecture design:        _bmad/bmad-dl-lifecycle/bmad-dl-architecture/SKILL.md
- Stage 4   — Task breakdown (INF/EXP):   _bmad/bmad-dl-lifecycle/bmad-dl-detailed-design/SKILL.md
- Stage 4.5 — Pre-experiment contract:    _bmad/bmad-dl-lifecycle/bmad-dl-techspec/SKILL.md
- Stage 5   — Infrastructure build:       _bmad/bmad-dl-lifecycle/bmad-dl-infra/SKILL.md
- Stage 6   — Training experiment:        _bmad/bmad-dl-lifecycle/bmad-dl-experiment/SKILL.md
- Stage 7   — Experiment analysis:        _bmad/bmad-dl-lifecycle/bmad-dl-analysis/SKILL.md
- Stage 7.5 — HPO (conditional):          _bmad/bmad-dl-lifecycle/bmad-dl-hparam/SKILL.md
- Stage 8   — Iterative revision:         _bmad/bmad-dl-lifecycle/bmad-dl-revision/SKILL.md

## Universal Tools (tell AI to follow these anytime)

- Search past experiments / warn:         _bmad/bmad-dl-lifecycle/bmad-dl-advise/SKILL.md
- Capture session learnings:              _bmad/bmad-dl-lifecycle/bmad-dl-retrospective/SKILL.md

## Experiment Tracking

Chosen tool: {tracking_tool}
Configure in bmad-dl-infra (Stage 5).

## LLM Engine

The model is set in your IDE settings — not here.
For scripts calling an LLM programmatically: configs/llm_config.yaml + scripts/llm_client.py

## Key Principles

- No packages installed until bmad-dl-infra (Stage 5) runs `uv sync`.
- Package requirements are written to pyproject.toml in bmad-dl-ideation (Stage 1).
- TECHSPECs are contracts — never modify after training starts.
"""

# ---------------------------------------------------------------------------
# CLAUDE.md template (Claude Code)
# ---------------------------------------------------------------------------
CLAUDE_MD_TEMPLATE = """\
# BMAD DL Lifecycle — Project Rules
# Auto-generated by bmad-dl-scaffold.

## Available Skills

Use /bmad-dl-<skill> to invoke any stage:

| Command | Stage | Role |
|---------|-------|------|
| /bmad-dl-ideation | 1 | Domain Expert — problem framing, PRD, package requirements |
| /bmad-dl-eda | 2 | Data Scientist — EDA, class weights, domain interpretation |
| /bmad-dl-architecture | 3 | AI Architect — model stack, tracking tool choice |
| /bmad-dl-detailed-design | 4 | Tech Lead — INF-* and EXP-* task breakdown |
| /bmad-dl-techspec | 4.5 | Domain Expert + Tech Lead — pre-experiment contract |
| /bmad-dl-infra | 5 | Developer + MLOps — build infra, run `uv sync` |
| /bmad-dl-experiment | 6 | Developer — execute EXP-* training runs |
| /bmad-dl-analysis | 7 | Data Scientist — evaluate vs TECHSPEC tiers |
| /bmad-dl-hparam | 7.5 | Data Scientist — HPO (conditional on baseline) |
| /bmad-dl-revision | 8 | Domain Expert + Tech Lead — amend all upstream docs |
| /bmad-dl-advise | any | Surface past findings before new work |
| /bmad-dl-retrospective | any | Capture session learnings |

## Experiment Tracking

Chosen tool: {tracking_tool}
Configure in bmad-dl-infra (Stage 5).

## LLM Engine

The model executing these skills is the one selected in your Claude Code model picker.
No project-level override needed.

For scripts that call an LLM programmatically:
  Config: configs/llm_config.yaml  (provider / model / api_key_env / base_url)
  Usage:  from scripts.llm_client import LLMClient

## Package Management

This project uses **uv**. Do NOT use pip or python -m venv.

- Add packages: `uv add <package>`
- Sync environment: `uv sync`
- Run scripts: `uv run python scripts/...`

Packages are added to pyproject.toml in bmad-dl-ideation (Stage 1).
The first `uv sync` runs in bmad-dl-infra (Stage 5) as part of the smoke test.
"""

# ---------------------------------------------------------------------------
# .gitignore
# ---------------------------------------------------------------------------
GITIGNORE = """\
# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.uv/

# uv
uv.lock

# Jupyter
.ipynb_checkpoints/
*.ipynb

# DL artifacts
checkpoints/
*.ckpt
*.pt
*.pth
*.onnx
*.tflite

# Experiment tracking
mlruns/
wandb/
logs/
*.log

# Data (keep structure, ignore content)
data/raw/*
data/processed/*
data/splits/*
!data/raw/.gitkeep
!data/processed/.gitkeep
!data/splits/.gitkeep

# Secrets
.env
*.env
secrets.json

# OS
.DS_Store
Thumbs.db
"""

# ---------------------------------------------------------------------------
# pyproject.toml skeleton (uv-compatible, no dependencies)
# ---------------------------------------------------------------------------
PYPROJECT_TEMPLATE = """\
[project]
name = "{project_name}"
version = "0.1.0"
description = "Generated by bmad-dl-scaffold. Add description after bmad-dl-ideation."
requires-python = ">={python_version}"
dependencies = []
# Dependencies are added in bmad-dl-ideation (Stage 1) and installed
# in bmad-dl-infra (Stage 5) via: uv sync

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
"""


def create_dirs(root: Path, project_name: str) -> None:
    dirs = [
        "docs/prd",
        "docs/eda",
        "docs/architecture",
        "docs/design",
        "docs/techspecs",
        "docs/implementation",
        "docs/experiments",
        "docs/revisions",
        "docs/knowledge",
        "data/raw",
        "data/processed",
        "data/splits",
        f"src/{project_name}",
        "tests",
        "scripts",
        "logs",
        "notebooks",
        "configs",
    ]
    for d in dirs:
        (root / d).mkdir(parents=True, exist_ok=True)

    # Placeholder files so git tracks empty dirs
    for d in ["data/raw", "data/processed", "data/splits", "logs"]:
        keep = root / d / ".gitkeep"
        if not keep.exists():
            keep.touch()

    # Minimal __init__.py files
    for init_dir in [f"src/{project_name}", "tests"]:
        init_file = root / init_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text("", encoding='utf-8')


def write_clinerules(root: Path, ide: str, tracking_tool: str) -> None:
    content = CLINERULES_TEMPLATE.format(tracking_tool=tracking_tool)
    if ide == "claude-code":
        out = root / ".claude" / "CLAUDE.md"
        out.parent.mkdir(exist_ok=True)
        out.write_text(CLAUDE_MD_TEMPLATE.format(tracking_tool=tracking_tool), encoding='utf-8')
        print(f"  Wrote: .claude/CLAUDE.md")
    else:
        out = root / ".clinerules"
        out.write_text(content, encoding='utf-8')
        print(f"  Wrote: .clinerules")


def write_gitignore(root: Path) -> None:
    gi = root / ".gitignore"
    if not gi.exists():
        gi.write_text(GITIGNORE, encoding='utf-8')
        print(f"  Wrote: .gitignore")
    else:
        print(f"  Skipped: .gitignore (already exists)")


def write_pyproject(root: Path, project_name: str, python_version: str) -> None:
    pf = root / "pyproject.toml"
    if not pf.exists():
        pf.write_text(PYPROJECT_TEMPLATE.format(
            project_name=project_name,
            python_version=python_version,
        ), encoding='utf-8')
        print(f"  Wrote: pyproject.toml (no dependencies — added in Stage 1)")
    else:
        print(f"  Skipped: pyproject.toml (already exists)")


def write_python_version(root: Path, python_version: str) -> None:
    pv = root / ".python-version"
    if not pv.exists():
        pv.write_text(python_version + "\n", encoding='utf-8')
        print(f"  Wrote: .python-version ({python_version})")


def run_uv_init(root: Path, project_name: str) -> None:
    """Run `uv init` to initialise the project, then clean up uv's boilerplate."""
    pf = root / "pyproject.toml"
    existed_before = pf.exists()

    result = subprocess.run(
        ["uv", "init", "--name", project_name, "--no-readme", "--no-workspace"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        if not existed_before:
            print(f"  Warning: `uv init` failed ({result.stderr.strip()}). Will write pyproject.toml manually.")
        else:
            print(f"  Skipped: uv init (pyproject.toml already exists)")
        return

    print(f"  Ran: uv init")

    # uv init creates main.py — remove it, we use src layout
    main_py = root / "main.py"
    if main_py.exists():
        main_py.unlink()
        print(f"  Removed: main.py (using src/ layout instead)")

    # Overwrite uv's minimal pyproject.toml with our richer template
    # (only if this is a fresh init)
    if not existed_before:
        pf.unlink(missing_ok=True)  # will be re-written by write_pyproject


def write_llm_config(root: Path, skill_dir: Path) -> None:
    """
    Copy llm_config.yaml.template to configs/llm_config.yaml in the project.

    This config is ONLY for scripts that call an LLM programmatically via
    llm_client.py. The model running the SKILL.md agent prompts is set inside
    the IDE (Cline / Antigravity / Claude Code) — not here.
    """
    dest = root / "configs" / "llm_config.yaml"
    if dest.exists():
        print(f"  Skipped: configs/llm_config.yaml (already exists)")
        return

    template = skill_dir.parent / "configs" / "llm_config.yaml.template"
    if template.exists():
        shutil.copy2(template, dest)
        print(f"  Wrote: configs/llm_config.yaml (edit to configure programmatic LLM calls)")
    else:
        # Write a minimal inline fallback if the template wasn't found
        dest.write_text(
            "# bmad-dl LLM config — for scripts/llm_client.py only.\n"
            "# The agent model is set in your IDE settings.\n"
            "provider: anthropic\n"
            "model: claude-sonnet-4-6\n"
            "base_url: ~\n"
            "api_key_env: ANTHROPIC_API_KEY\n"
            "max_tokens: 8192\n"
            "temperature: 0.0\n",
            encoding='utf-8',
        )
        print(f"  Wrote: configs/llm_config.yaml (minimal fallback — template not found)")


def register_in_bmad_help(root: Path, skill_dir: Path) -> None:
    """
    Register all bmad-dl-lifecycle skills in _bmad/_config/bmad-help.csv.

    bmad-help.csv is the routing table that /bmad-help reads to tell users
    what to do next. If the CSV already has bmad-dl-lifecycle rows they are
    replaced with the current ones (handles upgrades and renames).
    """
    csv_path = root / "_bmad" / "_config" / "bmad-help.csv"
    if not csv_path.exists():
        print(f"  Skipped: {csv_path} not found (not a BMAD project root?)")
        return

    # Our canonical rows live next to this script's parent dir
    our_csv = skill_dir.parent.parent / "bmad-dl-lifecycle.csv"
    if not our_csv.exists():
        print(f"  Skipped: bmad-dl-lifecycle.csv not found in module root")
        return

    existing = csv_path.read_text(encoding="utf-8")
    our_rows = our_csv.read_text(encoding="utf-8").strip()

    # Remove any existing bmad-dl-lifecycle rows, then append current ones
    kept = [line for line in existing.splitlines() if not line.startswith("bmad-dl-lifecycle,")]
    updated = "\n".join(kept).rstrip() + "\n" + our_rows + "\n"
    csv_path.write_text(updated, encoding="utf-8")
    print(f"  Updated: _bmad/_config/bmad-help.csv (bmad-dl-lifecycle rows replaced)")


def copy_claude_skills(root: Path, skill_dir: Path) -> None:
    """
    Copy all bmad-dl SKILL.md + bmad-manifest.json files into .claude/skills/
    so that Claude Code can discover them as slash commands.

    Only called when --ide claude-code is specified.
    """
    skills_root = skill_dir.parent.parent  # bmad-dl-scaffold/scripts/ → bmad-dl-lifecycle/
    dest_root = root / ".claude" / "skills"
    dest_root.mkdir(parents=True, exist_ok=True)

    copied = []
    for skill_dir_src in skills_root.glob("bmad-dl-*/"):
        skill_md = skill_dir_src / "SKILL.md"
        manifest = skill_dir_src / "bmad-manifest.json"
        if not skill_md.exists():
            continue
        dest_skill = dest_root / skill_dir_src.name
        dest_skill.mkdir(exist_ok=True)
        shutil.copy2(skill_md, dest_skill / "SKILL.md")
        if manifest.exists():
            shutil.copy2(manifest, dest_skill / "bmad-manifest.json")
        copied.append(skill_dir_src.name)

    if copied:
        print(f"  Copied {len(copied)} skills → .claude/skills/ (slash commands now available)")
    else:
        print(f"  Warning: no skill files found to copy into .claude/skills/")


def copy_scripts(root: Path, skill_dir: Path) -> None:
    """Copy bmad-dl utility scripts (including llm_client.py) into project scripts/."""
    scripts_dir = root / "scripts"
    skill_root = skill_dir.parent  # parent of bmad-dl-scaffold/scripts/ → .antigravity/skills/

    copied = []

    # Always copy llm_client.py from our own scripts dir
    llm_client_src = skill_dir / "llm_client.py"
    if llm_client_src.exists():
        dest = scripts_dir / "llm_client.py"
        if not dest.exists():
            shutil.copy2(llm_client_src, dest)
            copied.append("llm_client.py")

    # Copy all other utility scripts from the skill collection
    for skill_scripts in skill_root.glob("bmad-dl-*/scripts/*.py"):
        # Skip test files and llm_client (already handled)
        if skill_scripts.name.startswith("test_") or skill_scripts.name == "llm_client.py":
            continue
        dest = scripts_dir / skill_scripts.name
        if not dest.exists():
            shutil.copy2(skill_scripts, dest)
            copied.append(skill_scripts.name)

    if copied:
        print(f"  Copied {len(copied)} utility scripts → scripts/")
    else:
        print(f"  No utility scripts found to copy (run from skill directory)")


def _ask(prompt: str, default: str, choices: list[str] | None = None) -> str:
    """Prompt the user for input, showing the default and optional choices."""
    if choices:
        options = "/".join(
            f"[{c}]" if c == default else c for c in choices
        )
        display = f"{prompt} ({options}): "
    else:
        display = f"{prompt} [{default}]: "
    try:
        answer = input(display).strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return answer if answer else default


def main() -> None:
    # Project name and root: always scaffold into the current working directory.
    root = Path.cwd()
    project_name = root.name.replace("-", "_").replace(" ", "_")

    print(f"\nbmad-dl-scaffold: Scaffolding '{project_name}' in {root}\n")

    # Interactive Q&A for all options
    ide = _ask(
        "IDE",
        "cline",
        choices=["claude-code", "cline", "cursor", "antigravity"],
    )
    tracking_tool = _ask(
        "Experiment tracking tool (can be changed in Architecture stage)",
        "undecided",
        choices=["wandb", "mlflow", "clearml", "undecided"],
    )
    python_version = _ask("Python version", "3.11")
    copy_scripts_flag = _ask("Copy bmad-dl utility scripts?", "yes", choices=["yes", "no"])

    print()

    print("Creating directory structure...")
    create_dirs(root, project_name)

    print("Writing config files...")
    write_clinerules(root, ide, tracking_tool)
    write_gitignore(root)
    write_python_version(root, python_version)

    print("Initialising uv project...")
    run_uv_init(root, project_name)
    write_pyproject(root, project_name, python_version)

    print("Writing LLM config...")
    script_dir = Path(__file__).parent
    write_llm_config(root, script_dir)

    print("Registering skills in bmad-help.csv...")
    register_in_bmad_help(root, script_dir)

    if ide == "claude-code":
        print("Copying skills to .claude/skills/ (enables slash commands)...")
        copy_claude_skills(root, script_dir)

    if copy_scripts_flag != "no":
        print("Copying bmad-dl utility scripts...")
        copy_scripts(root, script_dir)

    # IDE-specific next-step instructions
    if ide in ("cline", "cursor"):
        stage1_instruction = (
            '  Open your IDE and tell the AI:\n'
            '  "Follow the workflow in: _bmad/bmad-dl-lifecycle/bmad-dl-ideation/SKILL.md"\n'
            '  (All skill paths are listed in .clinerules for quick reference)'
        )
    else:
        stage1_instruction = "  Use slash command: /bmad-dl-ideation"

    print(f"""
✓ Project scaffolded at: {root}

Next steps:
  1. Set up environment: uv venv && source .venv/bin/activate  (or use uv run)
  2. Start Stage 1 — Domain Expert frames the problem:
{stage1_instruction}
     The agent determines required packages and writes them to pyproject.toml.
  3. Stage 5 (bmad-dl-infra) runs: uv sync  ← FIRST package installation.

Do NOT run `uv sync` or `uv add` before Stage 5.
""")


if __name__ == "__main__":
    main()
